[package]
name = "karlos"
version = "0.0.0"
edition = "2024"

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"

[lib]
name = "karlos"
path = "src/lib.rs"
test = false
doctest = false
bench = false

[workspace]
members = ["boot", "kernel", "shared"]
